### ISSUE TITLE
 information.Properties["System.Devices.ClassGuid"]  is null

### ISSUE THREAD

**Issue by Charltsing** [smourier/DeviceExplorer#2]
DeviceExplorer\Model\DeviceManagerItem.cs

line 57， fix:
var guid = information.Properties["System.Devices.ClassGuid"];
if (guid == null) return;
var classGuid = (Guid)information.Properties["System.Devices.ClassGuid"];

**Comment by smourier** [comment]
Hi,

Do you have the case of a device without the System.Devices.ClassGuid property key defined? That's unexpected. What kind of device is it?

**Comment by Charltsing** [comment]
I run it in windows 10 22h2, i click my disk name of disk drive list
Maybe it needs Windows 11 ?

![image](https://github.com/smourier/DeviceExplorer/assets/19963715/af51fece-0278-4193-9035-f71766303670)

![image](https://github.com/smourier/DeviceExplorer/assets/19963715/c48d4e2f-bbb1-4d78-9d22-96a7ce8a8fa0)

**Comment by smourier** [comment]
Hum, I test it under Windows 10 too, strange.

I guess this device is special... I've fixed the code and published a new release, thanks

**Comment by smourier** [comment]
Closed due to inactivity
