### ISSUE TITLE
COMException 0x800710DF

### ISSUE THREAD

**Issue by Charltsing** [smourier/DeviceExplorer#3]
![捕获](https://github.com/smourier/DeviceExplorer/assets/19963715/d3884d6e-a1ee-4403-a38b-7847a809a210)

**Comment by smourier** [comment]
Hi,

0x800710DF is ERROR_DEVICE_NOT_AVAILABLE but I can't reproduce that error, even with machines that don't have bluetooth devices.

What OS are you running?

**Comment by Charltsing** [comment]
> Hi,
> 
> 0x800710DF is ERROR_DEVICE_NOT_AVAILABLE but I can't reproduce that error, even with machines that don't have bluetooth devices.
> 
> What OS are you running?


windows10 22h2

**Comment by smourier** [comment]
I've added exception handling: https://github.com/smourier/DeviceExplorer/commit/7a4bf2bffcc296115dcc8dbc3e54c28ed5d505c5
